version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8.1

      - image: mysql:5.7.18
        environment:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: password

    working_directory: /go/src/github.com/popshootjapan/dogenzaka-server

    steps:
      - checkout

      - run:
          name: Install dockerize
          command: |
              wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linuxNaN-$DOCKERIZE_VERSION.tar.gz
              tar -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
              rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
              DOCKERIZE_VERSION: v0.5.0

      - run:
          name: Wait for db
          command: |
              dockerize -wait tcp://localhost:3306 -timeout 1m

      - restore_cache:
          keys:
              - glide-cache-{{ checksum "glide.lock" }}

      - run:
          name: Install dependencies
          command: |
              sudo apt-get install -y curl
              curl https://glide.sh/get | sh
              glide install

      - save_cache:
          key: glide-cache-{{ checksum "glide.lock" }}
          paths:
              - vendor
      
      - run:
          name: Test
          command: |
            go test test/* -v
